### ISSUE TITLE
Error: Missing where or truncate attribute in the options parameter of model.destroy.

### ISSUE THREAD

**Issue by pihomeserver** [DaftMonk/generator-angular-fullstack#1394]
Hello

Using the version 3.0.0-rc8 of the generator, with a fresh install, when i want to delete the user i have an error 500 with the following message :
```
Error: Missing where or truncate attribute in the options parameter of model.destroy.
    at [object Object].Model.destroy (/Users/xxx/Development/my-new-project/node_modules/sequelize/lib/model.js:2239:11)
```
It seems that code in the server/api/user/user.controller.js has to be replaced with :
```
/**
 * Deletes a user
 * restriction: 'admin'
 */
exports.destroy = function(req, res) {
  User.destroy({ where: {
    _id: req.params.id }
  })
    .then(function() {
      res.status(204).end();
    })
    .catch(handleError(res));
};
```

Is that correct ?

**Comment by wangchi** [comment]
@pihomeserver Yes, I have the same error, it should be replaced!

**Comment by Awk34** [comment]
This should be fixed in the latest release

**Comment by MichaelMarkieta** [comment]
This is still a problem with Sequelize and PostgreSQL.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | 5.11.1
npm | 3.8.6
Operating System | OS X 10.10.4

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | SCSS
Router | ui-router
Build Tool | Gulp
Client Tests | Mocha
DB | PostgreSQL
Auth | Y

**Comment by Awk34** [comment]
@MichaelMarkieta please open a separate issue with complete details
